import type { Metadata } from "next";
import { Inter } from "next/font/google";


import Navbar from "@/components/ui/navbar/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Mystry Message",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    
    <html lang="en">
     
         
        <body className={inter.className}>
          <Navbar/>
          {children}
          
          
        </body>
      
      
    </html>
  );
}
